[package]
version = "1.0.0"

title = "SunVec"
description="Put the sun where you want it, even in many places."
readme  = "docs/README.md"
repository = ""
category = "Lighting & Rendering"
keywords = ["daylight", "sun", "sunpath", "sky", "distant light"]

[dependencies]
"omni.kit.uiapp" = {}

[[python.module]]
name = "jolly.sunvec"
